add version to key pair
massalabs/massa-standards pull request #101
Opened 2023-07-14 08:21 UTC by Thykof

2023-07-17 08:13 UTC, ASAPSegfault requested changes

2023-07-17 08:13 UTC, ASAPSegfault commented on wallet/file-format.md
> +| PublicKey | Mandatory | Byte array | Public key prepended by it's version | [21, 126 ...] |
```suggestion
| PublicKey | Mandatory | Byte array | Public key prepended by it's version | [0, 21, 126 ...] |
```

2023-07-17 08:49 UTC, ASAPSegfault approved these changes

2023-07-28 06:11 UTC, gregLibert approved these changes

2023-07-28 06:11 UTC, merged