Bump version to prepare release
massalabs/massa-standards pull request #160
Opened 2024-06-07 13:25 UTC by leoloco

2024-06-07 13:52 UTC, peterjah approved these changes

2024-06-07 13:54 UTC, gregLibert requested changes
As discussed:
- the version number is inconsistent jumping from 0.1.1
- there are *-dev dependencies in the package.json file that needs to be fixed.

2024-06-10 15:58 UTC, Ben-Rey approved these changes

2024-06-11 07:08 UTC, gregLibert requested changes

2024-06-11 07:08 UTC, gregLibert commented on smart-contracts/package.json
>          "@massalabs/massa-sc-compiler": "^0.1.1-dev",
to fix?

2024-06-11 13:05 UTC, gregLibert approved these changes

2024-06-11 14:32 UTC, gregLibert approved these changes

2024-06-12 13:36 UTC, gregLibert approved these changes

2024-06-12 13:46 UTC, merged