updates README and add LICENCE and CONTRIBUTING
massalabs/massa-standards pull request #36
Opened 2023-03-29 10:28 UTC by gregLibert

2023-03-29 10:29 UTC, gregLibert commented
@qdrn cc

2023-03-29 14:21 UTC, gregLibert commented
> It looks nice. I would just mention docs.massa.net.

Readme updated

2023-03-29 16:48 UTC, Thykof requested changes

2023-03-30 12:52 UTC, gregLibert commented on README.md
> +To get started with the Massa Standard Definition project, please refer to the documentation in the `docs` directory. This documentation includes instructions for contributing to the project and impl
fixed

2023-03-30 12:53 UTC, gregLibert commented on README.md
> -can help you to format markdown files.
Why not adding it in a CI ?

2023-03-30 12:53 UTC, gregLibert commented on README.md
> -can help you to format markdown files.
(i would like people to focus on standard and not necessary on code practices ...)

2023-03-30 12:54 UTC, gregLibert commented on README.md
> +This project is licensed under the Apache 2.0 license. For more information, please refer to the `LICENSE` file.
fixed

2023-03-30 12:57 UTC, Thykof commented on README.md
> -can help you to format markdown files.
new issue created https://github.com/massalabs/massa-standards/issues/39

2023-03-30 12:57 UTC, Thykof approved these changes

2023-03-30 12:58 UTC, merged