valid dns entry
massalabs/massa-standards pull request #61
Opened 2023-06-18 11:48 UTC by B-Naoufal

2023-06-19 07:57 UTC, peterjah commented on smart-contracts/assembly/contracts/dns/__tests__/dns.spec.ts
> +    });
encapsulate these two tests in a "describe" section
descripbe("test dns name validity"
test ("valid dns name" ...
....
test("invalid dns name"....

2023-06-19 07:58 UTC, peterjah requested changes

2023-06-19 08:02 UTC, peterjah approved these changes

2023-06-27 12:13 UTC, Thykof approved these changes

2023-06-27 12:14 UTC, merged